name: build

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    # An Apple Silicon (arm64) runner is necessary to build aarch64-darwin.
    # Public repositories get free minutes on this runner.
    runs-on: macos-26
    strategy:
      # emacs-gpu is a test package.  It must not stop the emacs build.
      fail-fast: false
      matrix:
        package: [emacs, emacs-gpu]
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            experimental-features = nix-command flakes

      - uses: cachix/cachix-action@v17
        with:
          name: snglth
          # This repo secret is a Cachix auth token with write access to the
          # cache.
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # The post-build hook of cachix-action pushes the package and the
      # packages that it uses to the cache after each build.
      - run: nix build .#${{ matrix.package }} --print-build-logs
